### ISSUE TITLE
Teach `OutliersTransform` to create a binary flag

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna#1018]
### 🚀 Feature Request

Teach `OutliersTransform` create binary flag for regular and anomaly points 

### Proposal

1. In `OutliersTransform` add parameter `add_flag: bool = False` 
2. Update the `transform`: now it should create binary flag 1 - outlier, 0 - regular if `add_flag=True`

### Test cases

Test that Transform works correctly in case of `add_flag=True`

**Comment by Mr-Geekman** [comment]
It doesn't seem really useful.
