### ISSUE TITLE
class AutoBase and AutoAbstract

### ISSUE THREAD

**Issue by martins0n** [tinkoff-ai/etna#1023]
### 🚀 Feature Request

* Auto and Tune share the same logic and methods 
* We should move it to unified class

### Proposal

* add class AutoBase with methods `fit`, `summary`, `top_k`
* add interface AutoAbstract with `fit`, `summary`, `top_k`, `objective `, `_init_optuna`
* inherit Auto from AutoBase

### Test cases

* refactor `test_auto` to test common methods of AutoBase where it's necessary

**Comment by GooseIt** [comment]
I'd like to take this issue after completing 1025.

**Comment by GooseIt** [comment]
What is the planned difference and similarities between classes Tune and Auto?
I believe that the code I have to write in AutoBase's `fit`, `summary`, `top_k` should implement general logic that will work for both class Tune and class Auto, am I right?
If so, I think that knowing expected functionality of class Tune will be beneficial to me.

**Comment by GooseIt** [comment]
Throughout ETNA code 'Base' classes are abstract classes, implementing part of its functions and leaving another part abstractmethods. In this issue, however, class Auto inherits neccessary abstractmethods from AutoAbstract, making adding abstractmethods to AutoBase redundant.
Would it be more appropriate to implement AutoBase class as AutoMixin (which will contain implementations of `summary`, `top_k`, `fit` and no abstractmethods)? Or, alternatively, remove AutoAbstract altogether, moving `_init_optuna` and `objective` to AutoBase as abstractmethods?
If I misunderstand proposed inheritance structure completely and proposed AutoBase/AutoAbstract functionalities are the best solution, would you please mind explaining me why?

**Comment by GooseIt** [comment]
As I currently understand it, classes `Tune` and `Auto` will have vastly different `fit` methods: the first is going to optimize hyperparameters for one selected Pipeline, while the second will pick the best-fitted pipeline from a user-determined pool without any hyperparameter optimization for any given pipeline. The question is:
Should `fit` method in AutoBase class be an abstractmethod, that later will be uniquely set separately in `Tune` and `Auto` classes?
Or should I rather strive to write `fit` method in such a way that it will work with both `Tune` and `Auto` classes without any overrides?
If I am wrong in my understanding, please correct me.

**Comment by martins0n** [comment]
> Should fit method in AutoBase class be an abstractmethod, that later will be overridden separately in Tune and Auto classes?
Yes, you're right

It's better to implement it mostly separately. In case they have something in common we will refactor it next.

In the future tasks `fit` in `Auto` will call `Tune.fit` for the best configs to be fine turned - so the logic will be more complicated

**Comment by GooseIt** [comment]
In case you worry that I left the project silently, I'm still working on the issue and will submit code tomorrow.
