### ISSUE TITLE
`set_params` method

### ISSUE THREAD

**Issue by martins0n** [tinkoff-ai/etna#1025]
### 🚀 Feature Request

Add method to change parameters of etna objects

### Proposal

* `BaseMixin.set_params`: `Callable[Dict] -> BaseMixin`
* It works like 
   `assert Pipeline(model=CatboostMultiSegmentModel(n_iterations=100)).set_params({'model.n_iterations': 1000}) == Pipeline(model=CatboostMultiSegmentModel(n_iterations=1000))`
* We suppose to make conversion via to_dict methods (dict -> patching dict -> creation new object from dict)

### Test cases

* check that set_params change params
* check if input dict have unknown parameters we do nothing

**Comment by GooseIt** [comment]
I'd like to take this issue. I'll start coding and report in one-three days.

**Comment by martins0n** [comment]
> I'd like to take this issue. I'll start coding, and I'll report in one-three days.

Ok. You're welcome

**Comment by GooseIt** [comment]
Should there be checks that the value assigned is of appropriate type? Or we'd rather let users be fully responsible for parameter-setting they do? 
As a concrete example, should 
`Pipeline(model=CatboostMultiSegmentModel(n_iterations=100)).set_params({'model': 1000})`
perform `model=1000`, or should it throw a TypeError instead?

**Comment by martins0n** [comment]
> Should there be checks that the value assigned is of an appropriate type? Or we'd rather let users be fully responsible for parameter-setting they do?

No, it's all on a user's responsibility.
