### ISSUE TITLE
Add `params_to_tune` method

### ISSUE THREAD

**Issue by martins0n** [tinkoff-ai/etna#1026]
### 🚀 Feature Request

For AutoML track we need knowledge of hyperparameters to tune for Transformers and Models and Pipelines.
We should add method `params_to_tune` to all classes.

### Proposal

* Add default method for `Transform` and `*AbstractModel`'s it should return empty dict
* Add to method to `AbstractPipeline`
* Add method for `Pipeline` it should iterate over transforms and model and collect all params.
* Add implementation for Ensemble and Stacking - raise `NotImplementedError`
* return value of `params_to_tune` is supposed to be like
```python
 params = {
    "model.n_iterations": optuna.distributions.CategoricalDistribution((10, 100, 200)),
    "transforms.0.mode": optuna.distributions.CategoricalDistribution(("per-segment", "macro")),
}
```

### Test cases

* check  default implementation for  `Transform` and `Models`
* check if Pipeline correctly combine params
* check if Ensemble and Stacking rise error

**Comment by Mr-Geekman** [comment]
Closed by #1073.
