### ISSUE TITLE
[BUG] AttributeError: 'NaiveModel'

### ISSUE THREAD

**Issue by vukeep** [tinkoff-ai/etna#1042]
### 🐛 Bug Report

при прохождении стартового мануала получаю ошибку AttributeError: 'NaiveModel' object has no attribute 'context_size'

### Expected behavior

future_ts = train_ts.make_future(future_steps=HORIZON, tail_steps=model.context_size)

Как исправить ошибку?

### How To Reproduce

HORIZON = 8
from etna.models import NaiveModel

# Соответствует модели
model = NaiveModel(lag=12)
model.fit(train_ts)

# Сделайте прогноз
future_ts = train_ts.make_future(future_steps=HORIZON, tail_steps=model.context_size)
forecast_ts = model.forecast(future_ts, prediction_size=HORIZON)

### Environment

python 3.9
etna: 1.13.0

### Checklist

- [x] Bug appears at the latest library version

**Comment by Mr-Geekman** [comment]
Привет
Работа с контекстом была добавлена в версии 1.14.0. В версии 1.13.0 ее еще не было. Про это есть в файле [`CHANGELOG.md`](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md#1140---2022-12-16). Если хочешь посмотреть мануал до того, как добавилась работа с контекстом, то посмотри [туториалы на версии 1.13.0](https://github.com/tinkoff-ai/etna/tree/1.13.0/examples). Ну или можно обновить библиотеку до версии 1.14.0.
