### ISSUE TITLE
Add `WAPE` metric

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna#1080]
### Proposal
1. Add function `wape` into `etna/metrics/functional_metrics.py`, see [wape](https://www.baeldung.com/cs/mape-vs-wape-vs-wmape)
2. Add class `WAPE` into `etna/metrics/metrics.py`
3. Add tests like for other metrics

### Discussed in https://github.com/tinkoff-ai/etna/discussions/1063

<div type='discussions-op-text'>

<sup>Originally posted by **prokofyev** January  9, 2023</sup>
Hello, dear developers!

I am interested why don't you have WAPE metric built-in in your ETNA library? I believe it would be highly popular and used.

Many thanks!</div>

**Comment by looopka** [comment]
hello, i'm want do it on weekend)

**Comment by alex-hse-repository** [comment]
@looopka Hi! Sounds great, feel free to ask any questions)
May you also assign yourself to this issue pls

**Comment by looopka** [comment]
I can't assign this issue to myself :(. 
last time, [iKintosh](https://github.com/tinkoff-ai/etna/issues/784) signed up for me.
if it's not difficult for you, fix it for me and https://github.com/tinkoff-ai/etna/issues/846
