### ISSUE TITLE
Fixes from inference track 

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna#1093]
## Proposal
1. Check that all the transforms have `test_save_load` test, add this test where necessary 
2. Fix tests in `test_models/test_inference` folder
3. Add tests for saving/loading for `HierarchicalPipeline` + `BaseReconciliator`

## Expected results
1. All transforms have `test_save_load` test
2. All tests from `test_models/test_inference` folder passed
3. `HierarchicalPipeline` + `BaseReconciliator` has tests for saving/loading

**Comment by Mr-Geekman** [comment]
Closed by #1096.
