### ISSUE TITLE
[BUG] additional_seasonality_params in prophet does not work

### ISSUE THREAD

**Issue by MGodgildieva** [tinkoff-ai/etna#1098]
### 🐛 Bug Report

When initializing Prophet model, setting 'additional_seasonality_params' as dict returns error:

AttributeError: '_ProphetAdapter' object has no attribute 'model'

Downgrading to 1.14 solves it.

### Expected behavior

This parameter should add custom seasonalities to Prophet

### Code
model = ProphetModel(additional_seasonality_params={'name':'monthly', 'period':30.5})
model.fit(train_ts)

future_ts= train_ts.make_future(HORIZON)
forecast_ts= model.forecast(future_ts)

### Checklist

- [X] Bug appears at the latest library version

**Comment by martins0n** [comment]
Thank your for bug report.

It seems we should change code in prophet.py like that and add some test cases
@MGodgildieva Maybe you have a time to fix this issue and make PR? I will help you if some issues arise

```
diff --git a/etna/models/prophet.py b/etna/models/prophet.py
index 51e4904..9b1b261 100644
--- a/etna/models/prophet.py
+++ b/etna/models/prophet.py
@@ -90,7 +90,7 @@ class _ProphetAdapter(BaseAdapter):
         )
 
         for seasonality_params in self.additional_seasonality_params:
-            self.model.add_seasonality(**seasonality_params)
+            model.add_seasonality(**seasonality_params)
 
         return model
```

**Comment by Mr-Geekman** [comment]
It looks like we already solved this problem.
```python
from etna.models import ProphetModel

HORIZON = 2


def main():
    model = ProphetModel(additional_seasonality_params=[{'name': 'monthly', 'period' :30.5, 'fourier_order': 2}])


if __name__ == "__main__":
    main()
```

This script works fine.
