### ISSUE TITLE
Add default `params_to_tune` for encoders transforms

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#1222]
### 🚀 Feature Request

Add default `params_to_tune` for timestamp transforms.

### Proposal

Suggested grid for `SegmentEncoderTransform`: None.

Suggested grid for `MeanSegmentEncoderTransform`: None.

Suggested grid for `OneHotEncoderTransform`: None.

Suggested grid for `LabelEncoderTransform`: 
```python
{
    "strategy": CategoricalDistribution(["new_value", "mean"]),
}
```

To discuss:
- Strategy "none" won't work properly for some models. For example, `LinearPerSegmentModel` will fail on `None` values during prediction.
  - It was decided not to add "none" to the grid.

### Test cases

Look at #1221. Check empty grid as well.

**Comment by ostreech1997** [comment]
Closed by #1242.
