### ISSUE TITLE
Colab python 3.10 compatibility check

### ISSUE THREAD

**Issue by martins0n** [tinkoff-ai/etna#1266]
### Checklist

- [X] I have searched the issues.
- [X] I have searched the docs.

### ❓ What is the issue?

In a few months colab have migrated from python 3.8 to python 3.10
It could cause some issues with not updating packages.

Etna depends on a large amount of libraries that increase probability of implicit compatibity issues.

So it seems we should run checks on etna's default notebooks

**Comment by Mr-Geekman** [comment]
## `get_started`

Steps:
- `pip install etna`
- restart environment
- run notebook
- works fine

Errors from pip:
- `arviz 0.15.1 requires scipy>=1.8.0, but you have scipy 1.7.3 which is incompatible`
  - we have a limit on scipy in pyproject.toml
- `prophet 1.1.2 requires holidays>=0.14.2, but you have holidays 0.13 which is incompatible`
  - colab by default uses other version of prophet and when we install holidays we break this dependency

## `backtest`

Steps:
- `pip install etna[prophet]`
  - `pip install etna` also works
- restart environment
- run notebook
- works fine

Errors from pip on `pip install etna[prophet]`:
- `arviz 0.15.1 requires scipy>=1.8.0, but you have scipy 1.7.3 which is incompatible`
  - we have a limit on scipy in pyproject.toml

## `NN_examples`

Steps:
- `pip install etna[torch]`
- restart environment
- run notebook
- works fine

Errors from pip on `pip install etna[torch]`:
- `arviz 0.15.1 requires scipy>=1.8.0, but you have scipy 1.7.3 which is incompatible`
  - we have a limit on scipy in pyproject.toml
- `prophet 1.1.2 requires holidays>=0.14.2, but you have holidays 0.13 which is incompatible`
  - colab by default uses other version of prophet and when we install holidays we break this dependency
- `torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.11.0 which is incompatible`
- `torchdata 0.6.1 requires torch==2.0.1, but you have torch 1.11.0 which is incompatible`
- `torchtext 0.15.2 requires torch==2.0.1, but you have torch 1.11.0 which is incompatible`
- `torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 1.11.0 which is incompatible`
  - colab by default uses torch-2.0
