### ISSUE TITLE
Integrate `Tune` into `Auto`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#1269]
### 🚀 Feature Request

It is probably a good idea to start tuning inside the `Auto.fit` if there are remaining trials.

### Proposal

Add parameter `top_k` into `Auto.__init__`
- It will be responsible for tuning some of `top_k` tried pipelines
- As an alternative, the parameter can be added into `Auto.fit` method
- Default should be `top_k=0` not to change current behavior

Change init of optuna
- Create subfolder for pool only

`Auto.fit`:
- Run checking pool of pipelines, start measuring time
- Check how many trials was made and compute remaining n_trials and timeout
- If we have resources left start running `Tune.fit` for `top_k` best pipelines:
  - Use n_trials = remaining n_trials / top_k
  - Use timeout = remaining timeout / top_k
  - Create `Tune`, set `experiment_folder` to be inside of `Auto`
  - Run tuning

`summary`:
- Collect the result from pool part and tune parts
- We should clarify in a summary which part each dict belongs to: pool, tuning for top-1, etc

`top_k`:
- Top should be from all the results: pool and tuning

Documentation: 
- We should explain how the class works. Current documentation is not enough.

To discuss:
- How do we want to add `top_k`?
- Do we need `experiment_folder`? We only use it for `study_name`.
- Don't we want to accept `PoolGenerator` in `pool` parameter?

### Test cases

- Fix current tests
- Add tests for handing of `Tune` logic inside `Auto`

**Comment by martins0n** [comment]
* How do we want to add top_k?
we can pass it via parameter
* Do we need experiment_folder? We only use it for study_name.
I guess we can use prefix in case of possible collisions
* Don't we want to accept PoolGenerator in pool parameter?
We already can pass I guess

**Comment by Mr-Geekman** [comment]
Closed by #1272.
