### ISSUE TITLE
Create notebook for `Auto` and `Tune`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#1274]
### 🚀 Feature Request

We should show how `Auto` and `Tune` work in our tutorials.

Current script with example isn't shown in our documentation.

### Proposal

Create a notebook with examples of usage of `Auto` and `Tune`. What should be covered:
- What `Tune` class does
  - How it works
    - What kind of hyperparameters are tried, `params_to_tune` method
    - How to write custom `params_to_tune` and check them
    - Runner: 
    - Storage: how to suspend and continue the tuning using storage
  - Example of tuning with some pipeline
  - Analysis
    - `summary`
    - `top_k`
- What `Auto` class does
  - How it works
    - Pool stage
    - Tuning stage
    - How stages are working inside `fit`, how resources are divided between them
  - Example of tuning with default pool

### Test cases

-

### Additional context

Blocked by #1269, #1273.

**Comment by martins0n** [comment]
It would be greate to visualise perfomance gain after running Auto.fit and highlight greedy part and fine turning part

**Comment by Mr-Geekman** [comment]
Closed by #1285.
