### ISSUE TITLE
Merge User Guide and API sections

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#1323]
### 🚀 Feature Request

Currently in our prototype #1319 User Guide and API sections are very similar. We should rething them.

### Proposal

- Extract guide "Installation guide for Apple M1 (ARM)" into Installation section
- Try to move info from user guide into API section
- Try to prune API section from classes that should be shown: private classes, mixins. This can be done for example by manually selection that should be shown like it is done in `numpy`, `pandas` and many other libraries. Or we can point out what kind of objects should be ignored.

**Comment by alex-hse-repository** [comment]
May be in the separate task we can create section about the base classes for developers

**Comment by alex-hse-repository** [comment]
<img width="736" alt="Снимок экрана 2023-07-25 в 14 56 33" src="https://github.com/tinkoff-ai/etna/assets/55380696/5855d777-501b-4c85-820f-690a92484b00">

**Comment by alex-hse-repository** [comment]
May be we can add separate section for native nets and nets from PTF

**Comment by alex-hse-repository** [comment]
Why do we have section with the base classes for Transforms, but not for Models?

**Comment by alex-hse-repository** [comment]
"Change-point transforms" and "Decomposition transforms:" are almost the same

**Comment by alex-hse-repository** [comment]
I guess we should try to filter more such cases, this method is actually king of provate
<img width="756" alt="Снимок экрана 2023-07-25 в 15 02 31" src="https://github.com/tinkoff-ai/etna/assets/55380696/e0264eea-15b6-4326-9259-e60e13c28364">

**Comment by alex-hse-repository** [comment]
Also kind of private class
<img width="714" alt="Снимок экрана 2023-07-25 в 15 04 51" src="https://github.com/tinkoff-ai/etna/assets/55380696/78a21e87-768e-4c65-8e66-9ecd56eb7615">

**Comment by alex-hse-repository** [comment]
Why saving then?
<img width="659" alt="Снимок экрана 2023-07-25 в 15 05 32" src="https://github.com/tinkoff-ai/etna/assets/55380696/4880b178-9837-4190-8ab8-da3995c30955">

**Comment by alex-hse-repository** [comment]
Is everything ok with rendering?
<img width="756" alt="Снимок экрана 2023-07-25 в 15 06 02" src="https://github.com/tinkoff-ai/etna/assets/55380696/7d843978-6bed-474e-bba7-5b26fed73577">

**Comment by Mr-Geekman** [comment]
Why aren't you commenting in PR?

**Comment by Mr-Geekman** [comment]
> Is everything ok with rendering? <img alt="Снимок экрана 2023-07-25 в 15 06 02" width="756" src="https://user-images.githubusercontent.com/55380696/255893682-7d843978-6bed-474e-bba7-5b26fed73577.png">

I don't know, I didn't change it. It is [how it looks in our current documentation](https://etna-docs.netlify.app/commands.html). I think it depends on how the table is styled in each theme.

**Comment by Mr-Geekman** [comment]
> Why saving then? <img alt="Снимок экрана 2023-07-25 в 15 05 32" width="659" src="https://user-images.githubusercontent.com/55380696/255893563-4880b178-9837-4190-8ab8-da3995c30955.png">

I don't understand what is the problem. Can you elaborate on this?

**Comment by Mr-Geekman** [comment]
> <img alt="Снимок экрана 2023-07-25 в 15 00 42" width="329" src="https://user-images.githubusercontent.com/55380696/255892487-12c73b22-f02b-4cd6-88fa-4916687f31b3.png"> Can we somehow improve sorting here?(in all the sections)

Can you explain what is the problem with this order? It is ordered by the order in the `Transforms` document.

**Comment by Mr-Geekman** [comment]
Closed by #1324.
