### ISSUE TITLE
Confidence intervals from error estimation from backtest

### ISSUE THREAD

**Issue by martins0n** [tinkoff-ai/etna#202]
### 🚀 Feature Request

We can build confidence intervals for generative models or models like Arima out of the box.
But we miss this opportunity for Regression models.
We should build intervals from backtest results for such models.

### Motivation

Confidence intervals are helpfull for risk estimation.

### Proposal

- Pipeline method `forecast` has  parameter `confidence_interval` by default False
- Pipeline `__init__` has parameters `interval_width` by default `0.95` and  `confidence_interval_cv` by default 3
- While forecast -- default implementation of confidence intervals is used, if it's not available -- we use another procedure
  -  Estimating errors on crossvalidation results using backtest
  -  confidence interva is given by (y_{i} - t_{\alpha} * SE,  y_{i} + t_{\alpha} * SE) - SE -- standart error estimation

### Checklist

- [X] Added feature request
- [X] Added motivation
- [X] Added proposal

**Comment by iKintosh** [comment]
If model already has confidence interval support then use model's method, otherwise use Pipeline's
