### ISSUE TITLE
[BUG] Outdated version of etna package

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#281]
### 🐛 Bug Report

With `pip install etna-ts` the last version is installed. However, with `pip install etna` only version 1.0.0.

### Expected behavior

The same behaviour for `pip install etna` and `pip install etna-ts`.

### How To Reproduce

Run `pip install etna`.

### Checklist

- [X] Bug appears at the latest library version

**Comment by iKintosh** [comment]
Now it seems to be fixed. I close this issue.
