### ISSUE TITLE
Rename `cv` to `n_folds`

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#290]
### 🚀 Feature Request

Parameter for number of folds in cross validation should be names `n_folds` throughout library.

### Motivation

Now we have inconsistent names for number of folds in our library. This should be fixed.

### Proposal

Rename all `cv` parameters into `n_folds`

### Test cases

No new tests needed

### Checklist

- [x] I discussed this issue with ETNA Team

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone already doing it?

**Comment by iKintosh** [comment]
Hi! No one is doing it at the moment. Feel free to take it.

**Comment by Carlosbogo** [comment]
I'm sorry, but it's the first time I work on this repository so I'm still trying to understand a lot of things.
I have been looking around for a bit but I'm still not sure if I understand what I need to change:

Do you mean that there are there different implementations of cross validation for different purposes that have inconsistent names for the number of parameters? If so, I haven't been able to find any of those implementations except for `TimeSeriesCrossValidation`.

**Comment by Mr-Geekman** [comment]
There are two implementations of cross validation: in `TimeSeriesCrossValidation` and in `Pipeline`. But parameter for number of folds also occurs in other classes, for example in `StackingEnsemble` (and there we can find an inconsistent name). We want to make sure that there are no other places including tests where names for number of folds are inconsistent.
