### ISSUE TITLE
[BUG] Disappearance of prefix "regressor_" with default value of out_column in transforms

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna#299]
### 🐛 Bug Report

In some transforms `out_column` is generated incorrectly when passing `inplace=False` without setting ` out_column` explicitly. List of transforms:
1. AddConstTransform
2. LogTransform
3. All WindowStatisticsTransforms
4. All SklearnTransforms 
5. TrendTransform

### Expected behavior

If `inplace=False` and `out_column=None` it should be set to `self.__repr__()` or `regressor_{self.__repr__()}` if the `in_column` is a regressor

### Code
```
from etna.transforms.power import YeoJohnsonTransform
from etna.datasets import TSDataset
from etna.datasets import generate_ar_df
import pandas as pd

df = generate_ar_df(periods=5,start_time="2000-01-01",n_segments=2,freq="H")
df_exog = generate_ar_df(periods=10,start_time="2000-01-01",n_segments=2,freq="H").rename({"target":"regressor_exog"},axis=1)
ts = TSDataset(df=TSDataset.to_dataset(df),freq="H",df_exog=TSDataset.to_dataset(df_exog))

transform = YeoJohnsonTransform(inplace=False)
transform.fit_transform(ts.df)

```

### Checklist

- [X] Bug appears at the latest library version

**Comment by iKintosh** [comment]
We won't fix this bug. 
Will rethink the whole regressor logic.
