### ISSUE TITLE
[BUG] DTWClustering cant be serialized

### ISSUE THREAD

**Issue by WinstonDovlatov** [tinkoff-ai/etna#307]
### 🐛 Bug Report

When i try to serialize DTWClustering object by dill or pickle, i get errors.

for pickle: Can't pickle <function simple_dist at 0x7fde4f5514c0>: it's not the same object as etna.clustering.distances.dtw_distance.simple_dist. 
It mast be some kind of name error

for dill: cannot pickle 'generator' object

### Expected behavior

DTWClustering can be serialized by dill and pickle

### Code

> dtw = DTWClustering()
> with open('path', 'wb') as fout:
>     dill.dump(dtw, fout)

> dtw = DTWClustering()
> with open('path', 'wb') as fout:
>     pickle.dump(dtw, fout)

### Checklist

- [X] Bug appears at the latest library version

**Comment by martins0n** [comment]
Some additional context:
We use numba generated cfuncs for DTW distance computation.

Current most common approaches like dill or standard pickle can't serialize cfuncs.

So we can change `numba.cfunc` to `numba.jit(nopython=True)` as a straightforward solution. 
It shouldn't affect perfomance dramatically.
