### ISSUE TITLE
Remove black and add flake8 plugins instead 

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#41]
### Motivation
Black does not comply with PEP (https://github.com/PyCQA/pycodestyle/issues/373, https://github.com/psf/black/issues/315)
Flake8 plugins could be tuned as we wish and does make developers pay more attention to code style. 

## Proposal
Remove black.
Add following plugins:

- https://github.com/m-burst/flake8-pytest-style

- https://github.com/MartinThoma/flake8-simplify

- https://github.com/PyCQA/flake8-commas
- https://github.com/adamchainz/flake8-comprehensions
- https://github.com/PyCQA/flake8-bugbear
- https://github.com/wemake-services/flake8-eradicate
- https://github.com/wemake-services/flake8-broken-line
- https://github.com/afonasev/flake8-return

- https://github.com/best-doctor/flake8-class-attributes-order

- https://github.com/sco1/flake8-annotations (only ANN301)

### Test cases
No need

### Alternatives
Keep as is

### Checklist
- [x] feature proposal description
- [x] motivation
- [x] extra proposal context / proposal alternatives review

**Comment by Mr-Geekman** [comment]
There is comments in Black's documentation about [E203](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#id1).

**Comment by iKintosh** [comment]
https://github.com/catalyst-team/codestyle#catalystcodestyle

**Comment by Mr-Geekman** [comment]
For checking NumPy codestyle:
* [pylint.extensions.docparams](https://github.com/PyCQA/pylint/blob/main/pylint/extensions/docparams.rst)
* [darglint](https://github.com/terrencepreilly/darglint) -- can be configured to work with [flake8](https://github.com/terrencepreilly/darglint#flake8).
