### ISSUE TITLE
Remove class BasePipeline

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#423]
### 🚀 Feature Request

Remove useless class BasePipeline

### Motivation

It is useless. Only Pipeline class inherits from it. And all the methods if BasePipeline class could be safely inserted in Pipeline class.

### Proposal

Insert into Pipeline class:
- _validate_quantiles method
- check_support_prediction_interval
- self.quantiles argument

### Test cases

No test cases needed

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by alex-hse-repository** [comment]
Done in issue #562
