### ISSUE TITLE
Speed up `TSDataset.to_flatten`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#472]
### 🚀 Feature Request

Make `TSDataset.to_flatten` faster.

### Motivation

Now there is cycle over segments, which seems slow. In some practical cases almost half of the time was spent on `select_dtypes` inside this cycle.

### Proposal

Make `TSDataset.to_flatten` vectorized.

Prototype:
```python
import pandas as pd
from etna.datasets import generate_const_df, TSDataset

regressors_timestamp = pd.date_range(start="2021-06-01", periods=50)
df_regressors_1 = pd.DataFrame(
    {"timestamp": regressors_timestamp, "regressor_1": 1, "regressor_2": 2, "segment": "segment_0"}
)
df_regressors_2 = pd.DataFrame(
    {"timestamp": regressors_timestamp, "regressor_1": 3, "regressor_2": 4, "segment": "segment_1"}
)
df_exog = pd.concat([df_regressors_1, df_regressors_2], ignore_index=True)
df_exog_ts_format = TSDataset.to_dataset(df_exog)

# current implementation
df_exog_flattened = TSDataset.to_flatten(df_exog_ts_format)

# new implementation prototype
df_unstacked = df_exog_ts_format.unstack().reset_index()
df_exog_flattened_alternative = df_unstacked.pivot(index=["timestamp", "segment"], columns=["feature"], values=[0])[0].reset_index()
df_exog_flattened_alternative.columns.name = None
```

### Test cases

1. Make sure that existing tests work correct.
2. Add test with regressors.
3. Add test with category dtypes.

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by Mr-Geekman** [comment]
Version in #475 is up to 3 times faster then original and seems to have very low changes. Test for performance
```python
def test_speed_flatten():
    # vectorized (broken): [1.38, 1.33, 1.35]
    # old faster: [11.76, 11.70, 11.98]
    # old: [33.28, 33.88, 36.35]
    import time

    df = generate_ar_df(start_time="2020-01-01", periods=100, n_segments=10_000)
    df_exog = df.copy()
    df_exog.rename(columns={"target": "exog_1"}, inplace=True)
    df_exog["exog_2"] = [1, 2, 3, 4, 5] * (df_exog.shape[0] // 5)
    df_exog["exog_2"] = df_exog["exog_2"].astype("category")

    ts = TSDataset(df=TSDataset.to_dataset(df), df_exog=TSDataset.to_dataset(df_exog), freq="D")

    time_start = time.time()
    df_flat = ts.to_pandas(flatten=True)
    time_finish = time.time()
    elapsed_time = time_finish - time_start
    print(f"{elapsed_time:.2f}")
```

Implementation at #475 running times are labeled with "old faster".

There is also a prototype vectorized implementation which gives times around 1.5s which is much faster then current solution. However, it has some problems with the second test. It leads to conversion of int category values to float category values.

Vectorized prototype implementation:
```python
# cast categories to object
dtypes = df.dtypes
category_columns = dtypes[dtypes == "category"].index.get_level_values(1).unique()
# flatten dataframe
df_flat = df.stack(level=0, dropna=False).reset_index().sort_values(by=["segment", "timestamp"]).reset_index(drop=True)
# mark category as category
df_flat[category_columns] = df_flat[category_columns].astype("category")
df_flat.columns.name = None
return df_flat
```

The problem occurs when we try to call `stack`: it leads to conversion of category values to int, which as a result leads to conversion to float because of NaNs in the beginning of one of the segments. Possible solutions:
1. Use conversion of category dtypes to object before calling stack. It solves the problem, but running times become about 30s, which gives us no improvement.
2. Somehow change `int64` to `Int64` dtype before calling stack and revert it later. The second dtype can handle NaNs without casting to `float64`.

Pandas [PR](https://github.com/pandas-dev/pandas/pull/40127) that can be relevant.

**Comment by iKintosh** [comment]
I consider this task closed since we are not going to touch this issue in a near future.

**Comment by iKintosh** [comment]
I consider this task closed since we are not going to touch this issue in a near future.
