### ISSUE TITLE
Create `PerSegmentBaseModel`, `PerSegmentPredictionIntervalModel`, `PerSegmentModel`

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#506]
### 🚀 Feature Request

Instead of one `PerSegmentModel` create three models

### Motivation

It will make abstractions easier to comprehend.

### Proposal

Create `PerSegmentBaseModel`
- it should inherit from `FitAbstractModel`
- It should implement method `fit` (actually it is already implemented in current PerSegmentModel)
- It should implement method `init` (already implemented in current PerSegmentModel)
- it should implement method `_build_models` (already implemented in current PerSegmentModel)
- it should implement method `get_models` that returns dict of all segment-models pairs
-  it should implement method `_forecast_segment` (already implemented in current Model), except it should expect additional parameters: `def _forecast_segment(model, segment: Union[str, List[str]], ts: TSDataset, *args, **kwargs) -> pd.DataFrame` and pass them to https://github.com/tinkoff-ai/etna/blob/1a10b256956352dd576ae8972771534c9ad47ed8/etna/models/base.py#L79

Create `PerSegmentPredictionIntervalModel`
- it should inherit from `PerSegmentBaseModel` and `ForecastPredictIntervalAbstractModel`
- It should implement method `forecast`, that passes prediction_interval, quantiles to model's predict method

Create `PerSegmentModel`
- it should inherit from `PerSegmentBaseModel` and `ForecastAbstractModel`
- It should implement method `forecast` (actually it is already implemented in current PerSegmentModel)

[Create](https://pypi.org/project/typing-extensions/) `FitPredictProtocol` as all these classes expect base_model to implement it.
- fit `def fit(self, df: pd.DataFrame, *args, **kwargs)`
- predict `def predict(self, df: pd.DataFrame, *args, **kwargs) -> pd.DataFrame`

Use `FitPredictProtocol` for typing in `PerSegmentBaseModel`: `model: FitPredictProtocol`
DO NOT use FitPredictProtocol for inheritance, FitPredictProtocol should be used only for type checks.

Also change the line
https://github.com/tinkoff-ai/etna/blob/1a10b256956352dd576ae8972771534c9ad47ed8/etna/pipeline/pipeline.py#L156
As it should check isinstance, not signature.

### Additional context

Blocked by #505 

Also future developers should note that FitPredictProtocol is for inner library use only. 
User guaranteed only fit-forecast interface stated by #505 and one should not worry about inner implementation of `PerSegmentBaseModel`, `PerSegmentPredictionIntervalModel`, `PerSegmentModel` and model adapters.

### Checklist

- [x] I discussed this issue with ETNA Team

**Comment by alex-hse-repository** [comment]
1. We refused to implement `FitPredictProtocol` because the type checking fails with args/kwargs in the signature.
2. Changes in Pipeline moved to #507
