### ISSUE TITLE
Make detrending polynomial

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#547]
### 🚀 Feature Request

There is a need to make detrending polynomial instead of linear. 

### Motivation

It will make possible to capture more difficult trends (e.g. quadratic).

### Proposal

1. Add `poly_degree` parameter to `_OneSegmentLinearTrendBaseTransform`, `LinearTrendTransform` and `TheilSenTrendTransform` that indicates the degree of the polynom to fit during detrending. Default value should be 1 and not change anything.

### Test cases

1. Add new fixtures with polynomial trend (degree=2) for one segment and many segments.
2. Test that fit_transform for one-segment model works with `poly_degree=2` on new fixture.
3. Test that fit_transform for all-segments model works with `poly_degree=2` on new fixture.
4. Test that inverse_transform for one-segment model works with `poly_degree=2` on new fixture.
5. Test that inverse_transform for all-segments model works with `poly_degree=2` on new fixture.

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by iKintosh** [comment]
Probably should use this https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html
