### ISSUE TITLE
[BUG] TSDataset.plot with given segments bug

### ISSUE THREAD

**Issue by julia-shenshina** [tinkoff-ai/etna#571]
### 🐛 Bug Report

TSDataset.plot with given series shows only 10 series instead of all given ones

### Expected behavior

TSDataset.plot(segments=[...]) shows all the given segments

### Code
```
from etna.datasets import generate_ar_df, TSDataset

flatten_df = generate_ar_df(periods=100, start_time="2020-01-01", n_segments=20)
df = TSDataset.to_dataset(flatten_df)
ts = TSDataset(df, freq="D")

ts.plot(segments = ts.segments)
```
### Screenshots
<img width="499" alt="Снимок экрана 2022-02-24 в 11 14 38" src="https://user-images.githubusercontent.com/25719410/155484830-27b1aa32-d87e-4790-92a6-91dc54b6f9c9.png">

### Checklist

- [X] Bug appears at the latest library version

**Comment by iKintosh** [comment]
I confirm, this a bug.
