### ISSUE TITLE
Add `NotImplementedError` to abstract methods

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna#585]
### 🚀 Feature Request

Replace `pass` to `NotImplementedError` in all the abstract methods

### Motivation

Abstract methods should raise this exception when they require derived classes to override the method

### Proposal

Replace `pass` to `NotImplementedError` in all the abstract methods

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by iKintosh** [comment]
It is not necessary because we use ABC package. 

```
from etna.models.base import Model

class ModelChild(Model):
    pass

ModelChild()

> Traceback (most recent call last):
>   File "...", line 3524, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-4-add2283b5471>", line 1, in <cell line: 1>
>     ModelChild()
> TypeError: Can't instantiate abstract class ModelChild with abstract methods fit, forecast

```

**Comment by alex-hse-repository** [comment]
Actually I created the issue after your [comment ](https://github.com/tinkoff-ai/etna/pull/578#discussion_r816826042))
