### ISSUE TITLE
Add feature importance method

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#621]
### 🚀 Feature Request

Models and Pipelines should have feature importance method.

### Motivation

It is useful way to analyse model robustness. It's a pity we don't have it.

### Proposal

All models that are able to return feature importance in some way (Catboost and LinearModels for example) should return this info in their default way. Other models that don't have feature importance metric should raise an error. 

In case of multisegment model we should expect `dict[segment_name, feature_importance object]`.

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by Mr-Geekman** [comment]
It is planned to do in continuation of [Interpretation track](https://github.com/tinkoff-ai/etna/milestone/24).
