### ISSUE TITLE
`sign` metric 

### ISSUE THREAD

**Issue by martins0n** [tinkoff-ai/etna#632]
### 🚀 Feature Request

We should add `sign` metric defined as  `mean(sign(y_true - y_pred))`. sign(0) == 0

### Motivation

Sometimes in case of transformation we get quite shifted forecasts.
It seems we can control this behaviour with such metrics.

### Proposal
- add functional metric `def sign(y_true: ArrayLike, y_pred: ArrayLike) -> float` to etna.metrics.functional_metrics
- add metric `class Sign(Metric)` to etna.metrics.metrics

### Test cases
- test `Sign` metric in both `macro` and `per-segment` modes
- test `Sign` in backtest 

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by julia-shenshina** [comment]
looks like we don't need test the metric in backtest as soon as we test both `macro` and `per-segment` modes in `__call__`
