### ISSUE TITLE
[Multivariabe prediction] Add target_to_exog function to utils

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#676]
### 🚀 Feature Request

Add function to utils that will allow duplicate segment's target as exog.features

### Motivation

It will make work with store branch datasets easier.

### Proposal

Function that will take original TSDataset 

`target_1 | target_2 | target_3`

and will turn it in TSDataset with exog data
```
target_1, exog_1 (target_2), exog_2 (target_3) | target_2, exog_1 (target_1), exog_2 (target_3) | target_3, exog_1 (target_1), exog_2 (target_2) 
```

Function should follow this signature:
```
def target_to_exog(
    ts: TSDataset
) -> TSDataset: 
```
Since ETNA expects same exogenous names for each segment, names of the original target will be deleted and names like exog_1, exog_2 etc will be created for exogenous data columns.

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by Mr-Geekman** [comment]
We will revisit this issue when developing multivariate time series forecasting.
