### ISSUE TITLE
Should we allow TSDataset to hold non-continuous series?

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#715]
### Checklist

- [X] I have searched the issues.
- [X] I have searched the docs.

### ❓ Questions and Help

Some tasks require us to delete some time periods from dataset (for example, the beginning of COVID in 2020). Should we allow our users to upload datasets with missing values as well?

**Comment by alex-hse-repository** [comment]
Will work on it in the separate track
