### ISSUE TITLE
Confidence intervals for time series and forecasts

### ISSUE THREAD

**Issue by mvakhmenin** [tinkoff-ai/etna#743]
### 🚀 Feature Request

Calculate confidence intervals for time series and forecasts, plot calculated ci

### Motivation

Greykite Library calculates confidence intervals for time series

### Proposal

Calculate confidence intervals for time series with certain significance levels. Calculate confidence intervals for a forecast with certain significance levels. Plot calculated confidence intervals together with time series and / or forecast if requested by a user.

### Alternatives

Confidence interval for time series can be plotted by Seaborn lineplot (https://seaborn.pydata.org/generated/seaborn.lineplot)
Confidence interval for time series can be calculated by Greykite library (https://linkedin.github.io/greykite/docs/0.1.0/html/pages/autodoc/doc.html#greykite.algo.uncertainty.conditional.conf_interval.conf_interval)

### Additional context

My implementation of confidence intervals calculation and plotting on a sample time series and forecast
https://colab.research.google.com/drive/1Qv4hkWnbjH0bSF7qd0ZcU5ogLdCxGmoe
Would like to contribute to ETNA library, but I just start working in Data Science and need some guidance

### Checklist

- [ ] I discussed this issue with ETNA Team

**Comment by martins0n** [comment]
Hi, it seems we already have empirical prediction intervals [implementation](https://github.com/tinkoff-ai/etna/blob/4fa63bcb4cecce7d803ea3c2b84d76063a3b3041/etna/pipeline/base.py#L220) like in greykite.

If it's not the same or has some errors or disadvantages.
Please tell us, we'll make task for improvements.


If you'd like to make first contribution and interested in uncertainty estimations, you can look at #739 and #738 tasks. 
We'll help you to make first PR

**Comment by mvakhmenin** [comment]
Hello,

I am not really interested in uncertainty estimations. I just could not find implementation of confidance intervals calculation and made it on my own. And thought, that it may be interesting for someone.

The main idea was to become a contributer for some good library. As I just begin my carrier in data science, I think, it could be a good line in my CV. Or may be I start working for Tinkoff.ai some day :o)

I made a PR for issue #741 . And going to settle out #461 . If there are some more simple issues appropriate for a beginner, pleas mark them as "good first issue".

This request can be closed

**Comment by martins0n** [comment]
🙏
