### ISSUE TITLE
Add ability to fill the NaNs with constant 

### ISSUE THREAD

**Issue by iKintosh** [tinkoff-ai/etna#784]
### 🚀 Feature Request

Change "zero" strategy in _OneSegmentTimeSeriesImputerTransform so it would allow to choose value that will be used to fill in NaNs. 

### Proposal

1. In class ImputerMode add new strategy called "constant"
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/etna/transforms/missing_values/imputation.py#L12-L19

2. Add new strategy "constant" to _OneSegmentTimeSeriesImputerTransform docsting
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/etna/transforms/missing_values/imputation.py#L41-L52

3. Add new argument "value: int = 0" to _OneSegmentTimeSeriesImputerTransform
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/etna/transforms/missing_values/imputation.py#L33

4. Add new argument "value" to TimeSeriesImputerTransform as well
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/etna/transforms/missing_values/imputation.py#L199-L206

5. Change docsting in init method of TimeSeriesImputerTransform

6. Add deprecation warning to zero strategy in _OneSegmentTimeSeriesImputerTransform
```python
if self.strategy == ImputerMode.zero:
    >>DeprecationWarning("zero strategy will be removed in etna 1.12.0. Use constant strategy instead." )<<
    self.fill_value = 0
```

7. Add new case to _OneSegmentTimeSeriesImputerTransform
```python
if self.strategy == ImputerMode.constant:
    self.fill_value = self.value
```

8. Make "constant" default strategy for _OneSegmentTimeSeriesImputerTransform instead of "zero"

After these changes we should be able to call 
```python
TimeSeriesImputerTransform(in_column="target",strategy="constant, value=42)
```

#### Change all tests with zero strategy to constant strategy with value=0
- Change `parametrize`
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L43
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L54
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L63
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L291
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L303
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L313
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L330
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L345

- Change argument 
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L84-L86
https://github.com/tinkoff-ai/etna/blob/687a1a9f955d87fe8fbc8c379d678e53aef94c24/tests/test_transforms/test_missing_values/test_impute_transform.py#L95-L97

```python
imputer = _OneSegmentTimeSeriesImputerTransform(..., strategy="constant", value=0, ...)
```

#### Add new test where value != 0 and check that everything work correctly.
Add new test/tests to test_impute_transform.py
How the test can look like:
```python
@pytest.mark.smoke  #so we run it every time, since this functionality is essential
def test_fill_value_with_constant_not_zero(df_with_missing_range_x_index: pd.DataFrame, fill_strategy: str):
    imputer = _OneSegmentTimeSeriesImputerTransform(
        in_column="target", strategy="constant", value=42
    )

# THE REST OF YOUR TEST CASE
```

**Comment by looopka** [comment]
Привет, хочется взять в работу эту задачку.

**Comment by iKintosh** [comment]
@looopka, yep, you can totally do that. Assigned this issue to you! ❤️

**Comment by looopka** [comment]
please let me know if i need to do something
