### ISSUE TITLE
[BUG] Teach `SeasonalMovingAverageModel` to work with out-sample predictions

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#789]
### 🐛 Bug Report

Currently `SeasonalMovingAverageModel` and `MovingAverageModel` don't pass some tests written in `test_inference`. Try also to make sure that in-sample predictions work as expected.

### Expected behavior

Tests are passed.

### How To Reproduce

Run tests in `test_inference`.

### Checklist

- [X] Bug appears at the latest library version

**Comment by GooseIt** [comment]
I've run the tests in `tests/test_models/test_inference` and after thorough examination have found that both `MovingAverageWindow` and `SeasonalMovingAverageWindow` pass all the tests.
However, upon examining these models more closely, I found two behaviours I believe to be bugs.
I link [Colab notebook with their reproduction and description](https://colab.research.google.com/drive/11f1z1BqUCu1c_93-96TxtmuyqbHbhcIb#scrollTo=BIkbZV4pNvhU).

**Comment by Mr-Geekman** [comment]
It seems that we already completed this particular task, I'm sorry we forgot to close it.

About colab notebook. It seems like you are confusing classes. There are two separate classes: `SeasonalMovingAverageModel` and `_SeasonalMovingAverageModel`. The first is etna model that works with `TSDataset`, the second is private class that holds implementation details and works with `pd.DataFrame`.

**Comment by Mr-Geekman** [comment]
It seems like this task is already done during Inference track.
