### ISSUE TITLE
parameter grid-search option within model fitting step

### ISSUE THREAD

**Issue by v-dumcki** [tinkoff-ai/etna#83]
### 🚀 Feature Request

With the structure of this package it seems like there is a great opportunity to further improve the model selection process using the existing cross-validation and metrics infrastructure by adding grid-search option to model fitting.  
I believe it would require only one more class function in the base model that could be called from either from the 'fit' function (i.e. if 'grid-search' selection was turned on) or a separate 'fit_grid_search'.
If there were any configurable parameters in the model, the function would test the combinations using the timeseries cross-validation settings, and fit the final model with the best performing parameters.  By default, for models without configurable parameter sets, it would just return the fitted model as it does now.

### Motivation

I'm currently working on developing tools to fit many models to a dataset and then basically select the best performing models for predictions.  The TSdataset, model, transform, and selection infrastructure in this package is excellent, but somewhat difficult to navigate externally.  I think it would be easier to add grid-search into the system (in instances where parameter ranges are relatively well defined), rather than expect users to struggle through finding a way to get it working outside the package.  

Alternatively, if someone believes there is an easy way to do grid search from outside the package, it would be great to add as an example notebook.

### Proposal

Identify parameter ranges and add these as class attributes at the model level.  Add fit_grid_search function to base model class to take in data, metrics, horizon, and search through the parameter sets with timeseries cv and then fit the final model with the best performing set.

### Test cases

perSegmentModels vs. multiSegmentModels
benchmarking performance with and without grid-search for each model

### Alternatives

Adding example notebooks explaining how to do grid-search of etna models manually using the framework.

### Checklist

- [x] Added feature request
- [x] Added motivation
- [x] Added proposal

**Comment by iKintosh** [comment]
We will add Optuna example in #288 and try to create OptunaRunner in #289. These issues are aimed to solve problem with params selection.

Also I propose we create GridSearchSelector for Transforms or Model selector. 

I summon @alex-hse-repository to suggest proper interface)

**Comment by Mr-Geekman** [comment]
We are currently doing [AutoML track](https://github.com/tinkoff-ai/etna/milestone/19) and the chosen path is very similar to the suggested here.
