### ISSUE TITLE
Change default `final_model` in `StackingEnsemble`

### ISSUE THREAD

**Issue by alex-hse-repository** [tinkoff-ai/etna#846]
### 🚀 Feature Request

Experiments show that linear regression with positive coefficients shows better results comparing with no restrictions to the coefficients. So it is better to change the default `final_model` in `StackingEnsemble` to `LinearRegression(positive=True)`

### Proposal

Change the default value to `LinearRegression(positive=True)` in the constructor of `StackingEnsemble` here:
https://github.com/tinkoff-ai/etna/blob/2b8a52724e50f47033dd60ff4b406dba7c18f5f0/etna/ensembles/stacking_ensemble.py#L93

**Comment by looopka** [comment]
let me take it issue?

**Comment by alex-hse-repository** [comment]
@looopka You can take any "Good first issue" you like)

**Comment by ostreech1997** [comment]
Closed by https://github.com/tinkoff-ai/etna/pull/1238
