### ISSUE TITLE
Fix order of columns after `TSDataset.to_flatten`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#873]
### 🚀 Feature Request

It can be useful to have a more strict rule about order of columns after `TSDataset.to_flatten`.

### Proposal

I propose the following order of columns:
* timestamp,
* segment,
* target,
* other columns in alphabetical order.

How it can be done:
1. Find [`TSDataset.to_flatten`](https://github.com/tinkoff-ai/etna/blob/master/etna/datasets/tsdataset.py#L536) method.
2. Move line `df_dict["segment"] = np.repeat(segments, len(df.index))` after the line `df_dict["timestamp"] = np.tile(df.index, len(segments))`.
3. Before `for column in columns` cycle:
    * Move value "target" at the beginning of `columns` list, 
    * Order other values in alphabetical order.

### Test cases

1. Fix doctest of `TSDataset.to_flatten`.
2. Fix docstes of `TSDataset.to_pandas`.
5. Make sure current test pass.
6. Add test on order of columns into [`test_dataset. test_to_flatten_with_exog `](https://github.com/tinkoff-ai/etna/blob/master/tests/test_datasets/test_dataset.py). 
    * The `expected_df` should be changed to have a correct order of columns.
    * Instead of 3 asserts at the end use `pd.testing.assert_frame_equal(obtained_df, expectged_df)`.

**Comment by GooseIt** [comment]
I'd like to take this issue, but I can't assign it to myself. Could you please assign it to me?

**Comment by GooseIt** [comment]
Shouldn't Test Cases 1 & 2 spell "doctext" instead of "doctest" and "docstes"?

**Comment by Mr-Geekman** [comment]
Doctest is correct name, I made a typo in second a line.
