### ISSUE TITLE
Add `FirstLastDifferenceTransform`

### ISSUE THREAD

**Issue by Mr-Geekman** [tinkoff-ai/etna#953]
### 🚀 Feature Request

Add `FirstLastDifferenceTransform`: it is a child of `WindowStatisticsTransform` that calculates the difference between last and first elements of the window.

### Proposal

1. Make class `FirstLastDifferenceTransform(WindowStatisticsTransform)`.
2. Define `def _aggregate`, so it takes difference between last and first elements.

### Test cases

1. Update `test_interface_simple`.
2. Update `test_fit_transform_with_nans`.
3. Make `test_first_last_difference_feature`

**Comment by alex-hse-repository** [comment]
The same as DifferencingTransform
