### ISSUE TITLE
ExpandingWindowSplitter, SingleWindowSplitter,  SlidingWindowSplitter

### ISSUE THREAD

**Issue by TDL77** [tinkoff-ai/etna#983]
### 🚀 Feature Request

ExpandingWindowSplitter, SingleWindowSplitter,  SlidingWindowSplitter
ссылка на ноутбук с примерами:
https://notebooks.githubusercontent.com/view/ipynb?browser=unknown_browser&color_mode=auto&commit=2819b03b5ccd9a91105c78610ab9e301c2ca426c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f736b74696d652f736b74696d652f323831396230336235636364396139313130356337383631306162396533303163326361343236632f6578616d706c65732f77696e646f775f73706c6974746572732e6970796e62&logged_in=false&nwo=sktime%2Fsktime&path=examples%2Fwindow_splitters.ipynb&platform=unknown_platform&repository_id=156401841&repository_type=Repository&version=0

### Proposal

Уважаемые разработчики , рассмотрите пожалуйста возможность добавления в ETNA , таких вариантов кросс-проверки , как ExpandingWindowSplitter, SingleWindowSplitter,  SlidingWindowSplitter, ...которые реализованы  в SKTIME
(sktime.forecasting.model_selection)

**Comment by Mr-Geekman** [comment]
It seems like we solved it in #990 by showing examples for implementation of such backtest strategies.
